### ISSUE TITLE
Tenant-Specific Configuration

### ISSUE THREAD

**Issue by dmtroyer** [saxifrage/learn#316] opened 2015-10-30 14:50 UTC
Thinking towards a multi-tenant strategy, there will be a number of fields and text that will need to be configured on a tenant by tenant basis.
- Tenant Name

I imagine there are a number of ways to do this, maybe it could be managed localization style in a yml file or possibly we could do this through the admin dashboard.

**Comment by dmtroyer** [comment] 2015-10-30 18:40
#285

**Comment by MatthewVita** [comment] 2015-11-07 00:10
closing dupe of https://github.com/saxifrage/cityasacampus/issues/285

**Closed as completed by MatthewVita** 2015-11-07 00:10 UTC
Labels: Meta, Development
