### ISSUE TITLE
Node is not clickable

### ISSUE THREAD

**Issue by timothyfcook** [saxifrage/learn#317] opened 2015-10-30 19:23 UTC
![screen shot 2015-10-30 at 3 22 48 pm](https://cloud.githubusercontent.com/assets/1823300/10855819/27fa035a-7f1a-11e5-80a0-3c380ee438df.png)

can click around node in the tile, but not on the node itself to bring up the card

**Comment by chadwhitacre** [comment] 2015-11-03 01:22
Dupe of #308.

**Closed as completed** 2015-11-03 01:22 UTC
Labels: ★★☆, map
