### ISSUE TITLE
Align Angular Data Model to Example

### ISSUE THREAD

**Issue by timothyfcook** [saxifrage/learn#97] opened 2015-04-28 21:41 UTC
https://github.com/saxifrage/learn/blob/master/examples/opportunity_instance_linked_data.json

Hopefully you and @justinxreese will meet in the middle on his #96

**Comment by justinxreese** [comment] 2015-05-12 16:06
Duplicate of https://github.com/saxifrage/learn/issues/106

**Closed as completed by justinxreese** 2015-05-12 16:06 UTC
