### ISSUE TITLE
pin down weekly meeting time

### ISSUE THREAD

**Issue by chadwhitacre** [saxifrage/learn#11] opened 2015-03-20 16:51 UTC
Thinking Friday sometime? 11am? 2pm?

**Comment by chadwhitacre** [comment] 2015-03-20 16:57
For venue I suggest Google Hangouts, because we can livestream/archive on YouTube and deeplink to decisions from relevant tickets.

**Comment by justinxreese** [comment] 2015-03-22 21:15
Duplicate of #32. That one has people tagged, so killing this one.

**Closed as completed by justinxreese** 2015-03-22 21:15 UTC
Labels: Meta
